PIN_ROOT := ${CURDIR}/../pin
CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
TOOLS_ROOT := $(PIN_ROOT)/source/tools
include $(CONFIG_ROOT)/makefile.config
include ${CURDIR}/makefile.rules
include $(CONFIG_ROOT)/makefile.default.rules